### PR TITLE
Updated NewsMapper to work with MapStruct dependency

### PR DESCRIPTION
**Pull request by anavduo**
Deleted the implementation of Service and added @Data from lombook 
Also refactor Dto in stead of DTO to be consistent

### CODE REVIEW

**Comment by pablofrankenn** [comment]
Looks good to me.

**Comment by anavduo** [comment]
I fixed the conflicts

**Comment by anavduo** [comment]
I reviewed the conflicts

**Comment by JonathanBolatti** [comment]
approved

**Pull request merged**
