### PR TITLE
OT147-60 Add Slide list in the endpoint Organization public

### PR DESCRIPTION
**Pull request by DanteIturri**
Add query custom in SlideRepository
add method in the SlideMapper
add method in the SlideService
Evidence for function
change in the organizationController endpoint("public/{id}")
evidencia 1

### CODE REVIEW

**Review by anavduo — COMMENTED** [review]
Have you add the service method?

**Comment by DanteIturri** [comment]
now add them I'm missing a commit

**Comment by DanteIturri** [comment]
> Have you add the service method?
now add them I'm missing a commit

**Comment by pablofrankenn** [comment]
Please pull main and refresh it. In your code are missing some methods(GetSlide from SlideService).

**Comment by DanteIturri** [comment]
I already updated the branch with the main one, it will not have any conflict

**Comment by pablofrankenn** [comment]
Looks good.  Great job.

**Pull request merged**
