### PR TITLE
Adding Post/testimonials

### PR DESCRIPTION
**Pull request by Lucasfranco1**
**SUMARY**

- Added TestimonialService
- Added TestimonialDto
- Added TestimonialMapper
- Added TestimonialController
- Added path in SecurityConfig

### CODE REVIEW

**Review by anavduo — COMMENTED** [review]
Good job! did you update already de main?

**Comment by JonathanBolatti** [comment]
good job, I liked the implementation of validations, we should implement a method to deal with errors and send them to the user's view

**Comment by Lucasfranco1** [comment]
> Good job! did you update already de main?

Yes!

**Comment by Lucasfranco1** [comment]
> good job, I liked the implementation of validations, we should implement a method to deal with errors and send them to the user's view

Great idea!

**Pull request merged**
